### PR TITLE
Add: Arabic language localization

### PR DESCRIPTION
**Pull request by asaah18**
"Localizable.strings" file has been created manually in a windows machine

### CODE REVIEW

**Comment by asaah18** [comment]
I will leave it to you to do any further actions, like renaming directory and project configuration adjustment

**Comment by asaah18** [comment]
Also, Arabic language is written from right to left

**Comment by afterxleep** [comment]
hey there!.  From your comments about changes made from a PC, I'm guessing you have not tested this yet, right?

**Comment by asaah18** [comment]
Yeah, I didn't test the change I made. As I don't have an access to a mac with excode installed. I will leave that to you 😅

**Comment by afterxleep** [comment]
I will test.  It's a little hard for me as I don't speak Arabic, and the app does not currently support LTR languages, but let me see what I can do!

**Comment by asaah18** [comment]
Ok, thank you
Please let me know if I can help you with anything. For example, testing the app using **TestFlight**.

**Pull request closed without merging**
